#!/bin/sh

# This module mounts RW partition to /var dir:
#     vardisk - specifies RW partition to be mounted to /var;

vardir_finish_hook_handler() {
    if [ "$1" = "pre" ] && [ "$2" = "finish" ]; then
        mount --move /var $ROOTFS_DIR/var
    fi
}

vardir_enabled() {
    if [ -z $bootparam_vardir_disk ]; then
        return 1
    fi

    return 0
}

vardir_run() {
    add_module_pre_hook "vardir_finish_hook_handler"

    mkdir -p /var
    mount ${bootparam_vardir_disk} /var
}
