desc: "Aos development setup for Renesas RCAR Gen3 hardware"
min_ver: "0.8"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOM0_BUILD_DIR: "build-dom0"
  DOMD_BUILD_DIR: "build-domd"
  DOMF_BUILD_DIR: "build-domf"
  XT_DOMD_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-domd.dtb"
  XT_XEN_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-xen.dtb"
  XT_OP_TEE_FLAVOUR: "generic_dt"
  GENERIC_MACHINE: "generic-armv8-xt"

  # Aos configuration
  AOS_BUNDLE_IMAGE_VERSION: "1.0.0"
  AOS_BUNDLE_REF_VERSION: "0.9.0"
  AOS_DOM0_IMAGE_VERSION: "%{AOS_BUNDLE_IMAGE_VERSION}"
  AOS_DOMD_IMAGE_VERSION: "%{AOS_BUNDLE_IMAGE_VERSION}"
  AOS_DOMF_IMAGE_VERSION: "%{AOS_BUNDLE_IMAGE_VERSION}"
  AOS_BUNDLE_OSTREE_REPO: "${TOPDIR}/../../rootfs_repo"
  AOS_DOMD_REF_VERSION: "%{AOS_BUNDLE_REF_VERSION}"
  AOS_DOMF_REF_VERSION: "%{AOS_BUNDLE_REF_VERSION}"
  AOS_BUNDLE_DOM0_TYPE: "full"
  AOS_BUNDLE_DOMD_TYPE: "full"
  AOS_BUNDLE_DOMF_TYPE: "full"

common_data:
  # Sources used by all yocto-based domains
  sources: &COMMON_SOURCES
    - type: git
      url: "git://git.yoctoproject.org/poky"
      rev: dunfell
    - type: git
      url: "git://git.openembedded.org/meta-openembedded"
      rev: dunfell
    - type: git
      url: "git://git.yoctoproject.org/meta-virtualization"
      rev: dunfell
    - type: git
      url: "https://github.com/xen-troops/meta-xt-common.git"
      rev: master
    - type: git
      url: "https://github.com/xen-troops/meta-xt-rcar.git"
      rev: master
    - type: git
      url: "https://github.com/aoscloud/meta-aos.git"
      rev: v5.2.1
    - type: git
      url: "https://github.com/xen-troops/meta-xt-prod-aos-rcar.git"
      rev: main

  # Common configuration options for all yocto-based domains
  conf: &COMMON_CONF
    - [SSTATE_DIR, "${TOPDIR}/../../../common_data/sstate"]
    - [DL_DIR, "${TOPDIR}/../../../common_data/downloads"]

    # Skip warning about missing "virtualization" distro feature
    - [SKIP_META_VIRT_SANITY_CHECK, "1"]

    # Use hypervisor console on all guests
    - [SERIAL_CONSOLES, "115200;hvc0"]

    # Aos configuration
    - [BOARD_MODEL, "%{AOS_BOARD_MODEL}"]
    - [BOARD_VERSION, "%{AOS_BOARD_VERSION}"]

  # Conf options for domain that are built used renesas layer
  domd_domf_conf: &DOMD_DOMF_CONF
    - [INIT_MANAGER, "systemd"]

    # add the static lib to SDK toolchain
    - [SDKIMAGE_FEATURES_append, " staticdev-pkgs"]

    # Remove ptest to reduce the build time
    - [DISTRO_FEATURES_remove, "ptest"]

    # HACK: force ipk instead of rpm b/c it makes troubles to PVR UM build otherwise
    - [PACKAGE_CLASSES, "package_ipk"]

    # Do not install kernel image to rootfs to decrease initrd size
    - ["RDEPENDS_${KERNEL_PACKAGE_NAME}-base", ""]

    # Initramfs configuration
    - [INITRAMFS_IMAGE, "core-image-tiny-initramfs"]
    - [INITRAMFS_IMAGE_BUNDLE, "0"]
    - [INITRAMFS_FSTYPES, "cpio.gz"]

components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      - *COMMON_SOURCES

    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - [MACHINE, "%{GENERIC_MACHINE}"]
        - [XT_DOMD_CONFIG_NAME, "%{XT_DOMD_CONFIG_NAME}"]
        - [XT_DOMD_DTB_NAME, "%{XT_DOMD_DTB_NAME}"]
        - [XT_XEN_DTB_NAME, "%{XT_XEN_DTB_NAME}"]
        - [XT_DOM_NAME, "dom0"]
        - [XT_GUEST_INSTALL, "domd domf"]

        # Disable HWDB which quite huge (around 15MB) and is not required at all
        - [BAD_RECOMMENDATIONS_append, " udev-hwdb"]

        # Remove unused DISTRO_FEATURES
        - [
            DISTRO_FEATURES_remove,
            "acl alsa argp pcmcia usbgadget
            usbhost opengl ptest multiarch wayland vulkan sysvinit",
          ]

        # Enable systemd on dom0
        - [INIT_MANAGER, "systemd"]

        # Do not install kernel image to rootfs to decrease initrd size
        - ["RDEPENDS_${KERNEL_PACKAGE_NAME}-base", ""]

        # Aos configuration
        - [BUNDLE_IMAGE_VERSION, "%{AOS_BUNDLE_IMAGE_VERSION}"]
        - [DOM0_IMAGE_VERSION, "%{AOS_DOM0_IMAGE_VERSION}"]
        - [DOMD_IMAGE_VERSION, "%{AOS_DOMD_IMAGE_VERSION}"]
        - [DOMF_IMAGE_VERSION, "%{AOS_DOMF_IMAGE_VERSION}"]
        - [BUNDLE_DIR, "${TOPDIR}/../../"]
        - [BUNDLE_OSTREE_REPO, "%{AOS_BUNDLE_OSTREE_REPO}"]
        - [BUNDLE_DOM0_TYPE, "%{AOS_BUNDLE_DOM0_TYPE}"]
        - [BUNDLE_DOMD_TYPE, "%{AOS_BUNDLE_DOMD_TYPE}"]
        - [BUNDLE_DOMF_TYPE, "%{AOS_BUNDLE_DOMF_TYPE}"]
        - [DOMD_REF_VERSION, "%{AOS_DOMD_REF_VERSION}"]
        - [DOMF_REF_VERSION, "%{AOS_DOMF_REF_VERSION}"]
        - [DOMD_MACHINE, "%{MACHINE}"]
        - [DOMF_MACHINE, "%{GENERIC_MACHINE}"]

      layers:
        - "../meta-virtualization"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-dom0"
        - "../meta-xt-common/meta-xt-control-domain"
        - "../meta-xt-rcar/meta-xt-rcar-dom0"
        - "../meta-aos"
        - "../meta-xt-prod-aos-rcar/meta-xt-prod-aos-rcar-dom0"

      build_target: core-image-thin-initramfs
      external_src:
        domd: "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/"
        domf: "%{YOCTOS_WORK_DIR}/%{DOMF_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/"

      additional_deps:
        - "%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
        - "%{DOMF_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/Image"

      target_images:
        - "tmp/deploy/images/%{GENERIC_MACHINE}/aos/version"
        - "tmp/deploy/images/%{GENERIC_MACHINE}/Image"
        - "tmp/deploy/images/%{GENERIC_MACHINE}/uInitramfs"

  domd:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "https://github.com/xen-troops/meta-renesas.git"
        rev: Renesas-Yocto-v5.1-patched
      - type: git
        url: "git://git.yoctoproject.org/meta-selinux"
        rev: dunfell

    builder:
      type: yocto
      work_dir: "%{DOMD_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - *DOMD_DOMF_CONF
        - [MACHINE, "%{MACHINE}"]
        - [SOC_FAMILY, "%{SOC_FAMILY}"]
        - [XT_DOM_NAME, "domd"]
        - [XT_OP_TEE_FLAVOUR, "%{XT_OP_TEE_FLAVOUR}"]
        - [XT_DEVICE_TREES, "%{XT_DOMD_DTB_NAME} %{XT_XEN_DTB_NAME}"]
        - [XT_GUEST_INSTALL, "domf"]

        # Configuration for USB 3.0
        # TODO: Enable this after validation
        #- [MACHINE_FEATURES_append, " usb3"]

        # Add Capacity Aware migration Strategy (CAS)
        - [MACHINE_FEATURES_append, " cas"]

        # Aos configuration
        - [DOMD_IMAGE_VERSION, "%{AOS_DOMD_IMAGE_VERSION}"]
        - [VIS_DATA_PROVIDER, "%{AOS_VIS_DATA_PROVIDER}"]

      build_target: core-image-minimal
      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-renesas/meta-rcar-gen3"
        - "../meta-virtualization"
        - "../meta-selinux"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-driver-domain"
        - "../meta-xt-rcar/meta-xt-rcar-fixups"
        - "../meta-xt-rcar/meta-xt-rcar-driver-domain"
        - "../meta-xt-rcar/meta-xt-rcar-domx"
        - "../meta-aos"
        - "../meta-xt-prod-aos-rcar/meta-xt-prod-aos-rcar-domx"
        - "../meta-xt-prod-aos-rcar/meta-xt-prod-aos-rcar-domd"

      target_images:
        - "tmp/deploy/images/%{MACHINE}/Image"
        - "tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
        - "tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
        - "tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"
        - "tmp/deploy/images/%{MACHINE}/core-image-minimal-%{MACHINE}.ext4"

  domf:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "git://git.yoctoproject.org/meta-arm"
        rev: dunfell
      - type: git
        url: "git://git.yoctoproject.org/meta-security"
        rev: dunfell

    builder:
      type: yocto
      work_dir: "%{DOMF_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - *DOMD_DOMF_CONF
        - [MACHINE, "%{GENERIC_MACHINE}"]
        - [PREFERRED_PROVIDER_virtual/kernel, "linux-generic-armv8"]
        - [XT_DOM_NAME, "domf"]
        - [XT_OP_TEE_FLAVOUR, "%{XT_OP_TEE_FLAVOUR}"]
        - [IMAGE_FSTYPES_append, " ext4"]

        # Aos configuration
        - [AOS_RUNNER, "crun"]
        - [DOMF_IMAGE_VERSION, "%{AOS_DOMF_IMAGE_VERSION}"]

      layers:
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-perl"
        - "../meta-openembedded/meta-python"
        - "../meta-virtualization"
        - "../meta-arm/meta-arm"
        - "../meta-arm/meta-arm-toolchain"
        - "../meta-security"
        - "../meta-xt-common/meta-xt-domu"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-aos"
        - "../meta-xt-prod-aos-rcar/meta-xt-prod-aos-rcar-domx"
        - "../meta-xt-prod-aos-rcar/meta-xt-prod-aos-rcar-domf"

      build_target: core-image-minimal
      target_images:
        - "tmp/deploy/images/%{GENERIC_MACHINE}/Image"
        - "tmp/deploy/images/%{GENERIC_MACHINE}/core-image-minimal-%{GENERIC_MACHINE}.ext4"
        - "tmp/work/generic_armv8_xt-poky-linux/core-image-minimal/1.0-r0/rootfs/var/aos/.unprovisioned"

images:
  full:
    type: gpt
    desc: "Full SD-card/eMMC image"
    partitions:
      boot_a:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 128 MiB
        files:
          "version": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/aos/version"
          "Image": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/Image"
          "uInitramfs": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/uInitramfs"
          "xen": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
          "xenpolicy": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
          "xen.dtb": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"

      boot_b:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 128 MiB
        files:
          "version": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/aos/version"
          "Image": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/Image"
          "uInitramfs": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/uInitramfs"
          "xen": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
          "xenpolicy": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
          "xen.dtb": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"

      boot_env:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: vfat
        size: 16 MiB

      domd_rootfs:
        gpt_type: B921B045-1DF0-41C3-AF44-4C6F280D3FAE # Linux aarch64 root
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/core-image-minimal-%{MACHINE}.ext4"
        size: 1024 MiB

      domd_var:
        gpt_type: 0FC63DAF-8483-4772-8E79-3D69D8477DE4 # Linux filesystem data
        type: ext4
        size: 1024 MiB

      domf-rootfs:
        gpt_type: B921B045-1DF0-41C3-AF44-4C6F280D3FAE # Linux aarch64 root
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/%{DOMF_BUILD_DIR}/tmp/deploy/images/%{GENERIC_MACHINE}/core-image-minimal-%{GENERIC_MACHINE}.ext4"
        size: 1024 MiB # Currently we do not have separate Aos partition for DomD. Make RW partition enough size to download updates

      domf_var:
        gpt_type: 0FC63DAF-8483-4772-8E79-3D69D8477DE4 # Linux filesystem data
        type: ext4
        size: 512 MiB
        files:
          ".unprovisioned": "%{YOCTOS_WORK_DIR}/build-domf/tmp/work/generic_armv8_xt-poky-linux/core-image-minimal/1.0-r0/rootfs/var/aos/.unprovisioned"

      domf_aos:
        gpt_type: 0FC63DAF-8483-4772-8E79-3D69D8477DE4 # Linux filesystem data
        type: ext4
        size: 1024 MiB

parameters:
  # Machines
  MACHINE:
    desc: "RCAR Gen3-based device"
    h3ulcb-4x2g-ab:
      default: true
      overrides:
        variables:
          MACHINE: "h3ulcb"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-h3ulcb-4x2g-ab.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
          XT_DOMD_DTB_NAME: "r8a77951-h3ulcb-4x2g-ab-domd.dtb"
          XT_XEN_DTB_NAME: "r8a77951-h3ulcb-4x2g-ab-xen.dtb"
          AOS_BOARD_MODEL: "h3ulcb-4x2g-ab"
          AOS_BOARD_VERSION: "1.0"

    h3ulcb-4x2g:
      overrides:
        variables:
          MACHINE: "h3ulcb"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-h3ulcb-4x2g.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
          XT_DOMD_DTB_NAME: "r8a77951-h3ulcb-4x2g-domd.dtb"
          XT_XEN_DTB_NAME: "r8a77951-h3ulcb-4x2g-xen.dtb"
          AOS_BOARD_MODEL: "h3ulcb-4x2g"
          AOS_BOARD_VERSION: "1.0"

    h3ulcb-4x2g-kf:
      overrides:
        variables:
          MACHINE: "h3ulcb"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-h3ulcb-4x2g-kf.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
          XT_DOMD_DTB_NAME: "r8a77951-h3ulcb-4x2g-kf-domd.dtb"
          XT_XEN_DTB_NAME: "r8a77951-h3ulcb-4x2g-kf-xen.dtb"
          AOS_BOARD_MODEL: "h3ulcb-4x2g-kf"
          AOS_BOARD_VERSION: "1.0"

        components:
          domd:
            sources:
              - type: git
                url: "https://github.com/CogentEmbedded/meta-rcar.git"
                rev: v5.1.0
            builder:
              layers:
                - "../meta-rcar/meta-rcar-gen3-adas"
                - "../meta-xt-rcar/meta-xt-cogent-fixups"
              conf:
                # Ignore OP-TEE patches as we have own OP-TEE
                - [BBMASK_append, "|meta-rcar-gen3-adas/recipes-bsp/optee"]

    m3ulcb:
      overrides:
        variables:
          MACHINE: "m3ulcb"
          SOC_FAMILY: "r8a7796"
          XT_DOMD_CONFIG_NAME: "domd-m3ulcb.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_m3"
          XT_DOMD_DTB_NAME: "r8a7796-m3ulcb-domd.dtb"
          XT_XEN_DTB_NAME: "r8a7796-m3ulcb-xen.dtb"
          AOS_BOARD_MODEL: "m3ulcb"
          AOS_BOARD_VERSION: "1.0"

    salvator-x-m3:
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7796"
          XT_DOMD_CONFIG_NAME: "domd-salvator-x-m3.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_m3"
          XT_DOMD_DTB_NAME: "r8a77960-%{MACHINE}-domd.dtb"
          XT_XEN_DTB_NAME: "r8a77960-%{MACHINE}-xen.dtb"
          AOS_BOARD_MODEL: "salvator-x-m3"
          AOS_BOARD_VERSION: "1.0"

    salvator-xs-m3-2x4g:
      # This is not misprint. This machine has 2x4 memory config
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7796"
          XT_DOMD_CONFIG_NAME: "domd-salvator-xs-m3-2x4g.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_m3_2x4g"
          XT_DOMD_DTB_NAME: "r8a77961-salvator-xs-2x4g-domd.dtb"
          XT_XEN_DTB_NAME: "r8a77961-salvator-xs-2x4g-xen.dtb"
          AOS_BOARD_MODEL: "salvator-xs-m3-2x4g"
          AOS_BOARD_VERSION: "1.0"

    salvator-xs-h3:
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-salvator-xs-h3.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3"
          XT_DOMD_DTB_NAME: "r8a7795-salvator-xs-domd.dtb"
          XT_XEN_DTB_NAME: "r8a7795-salvator-xs-xen.dtb"
          AOS_BOARD_MODEL: "salvator-xs-h3"
          AOS_BOARD_VERSION: "1.0"

    salvator-xs-h3-4x2g:
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-salvator-xs-h3-4x2g.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
          XT_DOMD_DTB_NAME: "r8a7795-salvator-xs-4x2g-domd.dtb"
          XT_XEN_DTB_NAME: "r8a7795-salvator-xs-4x2g-xen.dtb"
          AOS_BOARD_MODEL: "salvator-xs-h3-4x2g"
          AOS_BOARD_VERSION: "1.0"

    salvator-x-h3-4x2g:
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-salvator-x-h3-4x2g.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
          XT_DOMD_DTB_NAME: "r8a7795-salvator-x-4x2g-domd.dtb"
          XT_XEN_DTB_NAME: "r8a7795-salvator-x-4x2g-xen.dtb"
          AOS_BOARD_MODEL: "salvator-x-h3-4x2g"
          AOS_BOARD_VERSION: "1.0"

    salvator-x-h3:
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-salvator-x-h3.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3"
          XT_DOMD_DTB_NAME: "r8a7795-salvator-x-domd.dtb"
          XT_XEN_DTB_NAME: "r8a7795-salvator-x-xen.dtb"
          AOS_BOARD_MODEL: "salvator-x-h3"
          AOS_BOARD_VERSION: "1.0"

  # Aos VIS data provider
  VIS_DATA_PROVIDER:
    desc: "Sepecifieds plugin for VIS automotive data"
    telemetryemulator:
      default: true
      overrides:
        variables:
          AOS_VIS_DATA_PROVIDER: "telemetryemulatoradapter"

    renesassimulator:
      overrides:
        variables:
          AOS_VIS_DATA_PROVIDER: "renesassimulatoradapter"
